### ISSUE TITLE
Change column's type in data view won't affect the visulization

### ISSUE THREAD

**Issue by Erimus-Koo** [Kanaries/graphic-walker#100]
![image](https://github.com/Kanaries/graphic-walker/assets/17139670/e17243fb-e358-42e5-83e3-51bddd3542cf)

Change the dimension/measure in the Data view, but do not change in the visualization.

![image](https://github.com/Kanaries/graphic-walker/assets/17139670/d05eaa6d-3094-4cc1-acfb-a34eb34f1878)

**Comment by ObservedObserver** [comment]
For now, after you change the status in the data view, you need to add a new chart to make it work. The original chart will keep the previous status to prevent wrong state.

**Comment by Erimus-Koo** [comment]
Got it.

**Comment by Erimus-Koo** [comment]
I've tried to add a new view, and that works. But how to delete the old one?

**Comment by Erimus-Koo** [comment]
![image](https://github.com/Kanaries/graphic-walker/assets/17139670/22178caf-9834-4cfc-98fc-22a86fe94500)

I found that can directly drag between dimension and measure in chart view.
