### ISSUE TITLE
Pivot table: repeat labels

### ISSUE THREAD

**Issue by declann** [Kanaries/graphic-walker#115]
In pivot tables with multiple fields mapped to one axis, an option to repeat labels would help to make the table easier to scan.

e.g. in the following full adder truth table:

![Screenshot from 2023-07-30 22-41-26](https://github.com/Kanaries/graphic-walker/assets/353214/49d73c04-06df-4f23-aa86-e2fb555361fe)

**Comment by jojocys** [comment]
Do you mean add field name to the label to make it more easy to understand, in the above case, maybe:

+ A_in: 0
  + B_in: 0
  + B_in: 1
+ A_in: 1
  + B_in: 0
  + B_in: 1

**Comment by declann** [comment]
No but that would also be a nice option! (there are no headers on the Y axis, that should probably be a separate issue to discuss/address?)

What I mean is to be able to get a layout like this, where item labels repeat to make it easy to scan:

![image](https://github.com/Kanaries/graphic-walker/assets/353214/44834e86-ea54-4fbb-aaba-b1d5554dcb62)

I get this in LibreOffice using Repeat Item Labels option (though it is quite burried)

![image](https://github.com/Kanaries/graphic-walker/assets/353214/852244fc-af52-400b-845b-d0fb3dae012d)


In very detailed pivot tables, if we want to present them so they can be quickly scanned, this can be important.
