### ISSUE TITLE
[Bug] create a new chart, the data is not cleared.

### ISSUE THREAD

**Issue by Kikkon** [Kanaries/graphic-walker#156]
## First chart

![image](https://github.com/Kanaries/graphic-walker/assets/19528375/7f8da599-0e27-4723-9ab2-bf052f225df9)

## Create a new chart: 

![image](https://github.com/Kanaries/graphic-walker/assets/19528375/1485d8df-a4bf-490f-9712-d2a7c4547d20)

the data from the previous chart still exists.

**Comment by ObservedObserver** [comment]
solved
