### ISSUE TITLE
Sample examples for Graphic walker plugin.

### ISSUE THREAD

**Issue by goutham45** [Kanaries/graphic-walker#222]
Hi  @AntoineYANG can you please provide some sample examples on how to use this Graphic walker in React.

**Comment by ObservedObserver** [comment]
https://github.com/ObservedObserver/graphic-walker-examples

**Comment by goutham45** [comment]
Hi @AntoineYANG as you had provided for react and next. Is there any documentation or examples on how to use in Angular as well?
