### ISSUE TITLE
[BUG]Offset appears while dragging 'field' pill

### ISSUE THREAD

**Issue by Asm-Def** [Kanaries/graphic-walker#24]
I recently embedded Graphic Walker in Jupyter Notebook (https://github.com/Kanaries/pygwalker).

Then I found Top Tabbars and Left Sidebars always cause a strange offset while dragging pills from the field list, see the GIF

![Feb-20-2023 12-53-27](https://user-images.githubusercontent.com/8137814/220012453-79fec632-f578-4fc4-9d14-debc6ca1dd94.gif)

**Comment by AntoineYANG** [comment]
I consider that it may be relative to this issue in `react-beautiful-dnd`
https://github.com/atlassian/react-beautiful-dnd/issues/1881

**Comment by ObservedObserver** [comment]
fixed in https://github.com/Kanaries/graphic-walker/commit/77cc0e6735541d9d9196665c8076a2251e34565c

**Comment by ObservedObserver** [comment]
It seems fixes another situation (for a fixed or transformed container) not the one in JuypterLab.

**Comment by ObservedObserver** [comment]
fixed
