### ISSUE TITLE
Switching between measure and dimension

### ISSUE THREAD

**Issue by soilstack** [Kanaries/graphic-walker#25]
I'm experimenting with gwalker inside Jupyter notebook.  

```
df = pd.read_csv('./bike_path.csv', parse_dates=['datetime'])
gwalker = pyg.walk(df, hideDataSourceConfig=False)
```
There doesn't seem to be a way in the UI to shift a field from it's current designation (as a measure) to the other designation(dimension) or vice versa.

How do I control how an arbitrary column is interpreted by Gwalker. 

And in a related question,  if my original dataframe has a 'datetime' column, but in a visualiization I might want to use datetime.month or datetime.year,  is there anyway to specify that use in the UI, or do I need to specify new columns in the df (month,  year, etc) ?

Thanks

**Comment by ObservedObserver** [comment]
If you want to change a field from dimension to measure, just drag the field to the segment you want.

For datetime transformation, it is not supported yet. Usually, I make column transformation in host env of graphic-walker, like [Rath](https://github.com/Kanaries/Rath) or Juypter.

But I believe it is a good idea to support different datetime aggregation level in graphic-walker.
