### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by TDL77** [Kanaries/graphic-walker#26]
for vs code application does not work? what about the dark theme?

![image](https://user-images.githubusercontent.com/69913933/220839443-0256e1a9-cde5-428a-9ca9-e88aafeaf0b9.png)

**Comment by ObservedObserver** [comment]
Will be fixed in out recent milestone which redesign the UI

**Comment by ObservedObserver** [comment]
https://github.com/Kanaries/graphic-walker/pull/31

It is fixed in the latest version of `graphic-walker`, will be available in `pygwalker` in hours.
![gw-dark-scatter](https://user-images.githubusercontent.com/22167673/221626144-0bfd3eba-2ec1-47fb-9377-4e1523693700.png)

**Comment by ObservedObserver** [comment]
Use pygwalker with auto-theme (based on your device) in the latest version. pip install --upgrade "pygwalker>=0.1.4.6"
