### ISSUE TITLE
Notebook froze when loading a 0.5 Gb into a walk object in `pygwalker`

### ISSUE THREAD

**Issue by jojocys** [Kanaries/graphic-walker#29]
GW performance problem.
+ [x] computation performance
+ [ ] render performance
+ [x] RAM usage
+ [x] main thread tasks optimize

**Comment by ObservedObserver** [comment]
In release 0.2.19, graphic-walker improve its capacity of amount of data.
+ computations to webworker
+ remove visual-insights cube
