### ISSUE TITLE
Mouse delay and UI enhance request

### ISSUE THREAD

**Issue by jojocys** [Kanaries/graphic-walker#30]
> But the interface is a little wonky inside of my Jupyter notebook. All the buttons on the side look kinda faint, and the GUI looks small with everything at a small font size. Also there is a mouse delay. I'm sure a lot of these problems could be solved on my end, but the package seems to work a lot better in the Google or Kaggle notebooks.

From Reddit user's [comment](https://www.reddit.com/r/datascience/comments/117bptb/comment/j9md5dc/?utm_source=share&utm_medium=web2x&context=3)

**Comment by ObservedObserver** [comment]
fixed
