### ISSUE TITLE
Charts stuck in a small size, will flash larger and then back to small again

### ISSUE THREAD

**Issue by dthompson-maystreet** [Kanaries/graphic-walker#304]
On using the React graphic walker component (which is fabulous, by the way!) we've got an issue with the chart sizes being stuck matchbox-size in our UI. 

Container mode doesn't work either. 

However, oddly enough, when clicking some buttons, such as Axis Resizing, the chart will expand to the full size and then shrink back to the small size automatically after around half a second.

Please see attached video.

We're using v0.4.41 of the @kanaries/graphic-walker component, running pretty much inside a standard Craco app. If we disable our CSS no difference is seen in the behaviour.

Thank you very much in advance.

https://github.com/Kanaries/graphic-walker/assets/83958505/a5916ed5-db52-4465-bd03-86ac46f2f903

**Comment by dthompson-maystreet** [comment]
As a note, also happens on the public website at https://graphic-walker.kanaries.net/ - I used the Cars demo dataset. Chrome browser, version 120.0.6099.234 (Official Build) (arm64)

**Comment by islxyqwe** [comment]
It seems the parseRect function doesn't work properly when you set the pixel ratio to 1. I will fix it soon.

**Comment by islxyqwe** [comment]
@dthompson-maystreet it should be fixed in 0.4.46.

**Comment by dthompson-maystreet** [comment]
@islxyqwe thank you so much for looking into this and fixing it so quickly. Much appreciated!
