### ISSUE TITLE
Multi-Index

### ISSUE THREAD

**Issue by firmai** [Kanaries/graphic-walker#329]
Hi this would be very useful in the world of finance if you support multi-indexes. 

(1) My data is for example, Ticker, Date, Financial Statement Features. What one want's to do is to see say accounting scatterplot between total_assets, or correlation between etc.
(2) An ability to change the parameter in pygwalker to only have the data explorer and filterer without visualization, or a way to make sure that on run the data table appears first.

Thanks for your hard work

**Comment by jojocys** [comment]
You can use components in graphic walker independtly, we have a playground contains all examples of those components here: https://graphic-walker.kanaries.net/examples/TableWalker
