### ISSUE TITLE
LICENSE v LICENCE2 confusion

### ISSUE THREAD

**Issue by declann** [Kanaries/graphic-walker#330]
Hi,

I'm confused about how LICENSE2 applies. Is it a license only for logos? => if you do not use Kanaries logos it isn't relevant?
Or is it a license which is intended to add additional restrictions to graphic walker overall. If that's the case, I guess it would be useful if not critical to add clarity, but IANAL. +if that's the case, is Apache 2.0 a meaningful label to associate with the repo?

![image](https://github.com/Kanaries/graphic-walker/assets/353214/97e15730-e2cf-4e2d-b506-9e8561d525a3)

**Comment by ObservedObserver** [comment]
It is required not to apply any changes/remove to the logos in graphic-walker.

The software is basically under apache2 except the logo part. This is a common aproach in many open source softwares and make it more sustainable for the project.
