### ISSUE TITLE
pivot table limited to 2 dimensions per axis

### ISSUE THREAD

**Issue by declann** [Kanaries/graphic-walker#344]
Hi,

Neat possibility with pivot table is mapping many dimensions.

It seems GW is now restricted to 2 dimensions per channel: this is reasonable for Vega charts, but the pivot table can be more flexible.
This used to be the case e.g. in my image in https://github.com/Kanaries/graphic-walker/issues/115 , where I have 3 dimensions mapped to Y axis. I can no longer reproduce this using https://graphic-walker.kanaries.net/

Perhaps the dimension limit should be conditional on chart type, and then this will work, or do you think the restriction was introduced for a different reason?

Related #329 

Thanks!
Declan

**Comment by ObservedObserver** [comment]
Hi @declann , it indeed is a bug of graphic-walker, pivot-table should contains dimension limitation. The bug will be fixed this week in version `0.4.56`

**Comment by declann** [comment]
Thanks Elwynn!
