### ISSUE TITLE
Axis zoom is very restrictive

### ISSUE THREAD

**Issue by user529481** [Kanaries/graphic-walker#36]
Is there someway to manage my zoom in only on the y-axis? The variability of my data is in the 0.001% range and it just looks like a straight line no matter how much I zoom because the zoom appears to be locked on both the x and y axis. 

Also it appears to default to have y=0 on the bottom, my values are in the 10^6 and again it makes things look like straight line.

**Comment by k6sdevbob** [comment]
@danre07  I'd like to add a pair of new configurable fields (for x and y axis individually) to allow the corresponding axis to disable the default baseline settings which ensures that "0" is included in the viewport. (in your case, that makes no sense) I'd like to take it as a graphic-walker's issue and do some enhancement around.

About zooming on only one of the axes, i'll also be searching for a solution but i'm not sure about that. I suppose that the feature above may solve this problem.
