### ISSUE TITLE
Custom the chart style by config

### ISSUE THREAD

**Issue by islxyqwe** [Kanaries/graphic-walker#382]
Allow user to override the chart style by using a vega-lite config json, so user can use a json like
```
{
    "axis": {
        "labelAngle": 0
    }
}
```
to make the axis label in the chart display horizontal.

**Comment by BHznJNs** [comment]
I guess that I just preliminarily completed this feature? Please have a look.

This is where the users can chooses their vega config json file
![屏幕截图 2024-05-09 201153](https://github.com/Kanaries/graphic-walker/assets/67158072/3d75c6d4-060a-478b-b548-f9409f48eca6)

This is the content of config
![code](https://github.com/Kanaries/graphic-walker/assets/67158072/ec3b3df6-62a5-4ce7-a5c5-50faffdd397f)

This is the rendered appearance
![屏幕截图 2024-05-09 201208](https://github.com/Kanaries/graphic-walker/assets/67158072/7c6317bd-f497-4e74-b827-b520122e5f08)
