### ISSUE TITLE
Document how to change to Data tab programmatically?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Kanaries/graphic-walker#418]
In Pygwalker you can set the `default_tab`. I've tried to reverse engineer what goes on on the js side without luck.

I would like to set the default tab to 'data', i.e. somehow provide it to

```jsx
<GraphicWalker
    storeRef={storeRef}
    ref={graphicWalkerRef}
    data={transformedData}
    fields={fields}
    computation={computation}
    appearance={appearance}
    vizThemeConfig={theme}
    {...config}
   />
```

or set it via `graphicWalkerRef` or similar.

See https://github.com/panel-extensions/panel-graphic-walker/blob/main/src/panel_gwalker/_gwalker.js for the full code.

Ideally I would like to be able to get and set it on the python side too such that we have the bi-directional synchronisation below:

![image](https://github.com/user-attachments/assets/2f021884-0631-4549-b067-64e9a6eaa4e1)

My preliminary PR is here https://github.com/panel-extensions/panel-graphic-walker/pull/25.

**Comment by islxyqwe** [comment]
You can use the `setSegmentKey` function of the storeRef, e.g.
```
import { ISegmentKey } from "@kanaries/graphic-walker";
// enum ISegmentKey {
//     vis = 'vis',
//     data = 'data',
//     chat = 'chat',
// }
// ...
useEffect(() => {
    storeRef.current?.setSegmentKey(ISegmentKey.vis);
}, []);
// ...
```

**Comment by MarcSkovMadsen** [comment]
Works for my application. Thx.
