### ISSUE TITLE
Using graphic-walker in angular application

### ISSUE THREAD

**Issue by ZeeshanOfficial97** [Kanaries/graphic-walker#46]
Hi

I want to use this library in an angular application. But I am unable to find any helpful implementation. I am also trying to use react component in angular but am still unable to use it properly, it gives errors for the library

Does anyone have any idea regarding this how can i implement this library in an angular application and start using this for different feature development purposes?

**Comment by ObservedObserver** [comment]
You can wrap the Graphic Walker component in a pure js function to specify a root dom element to it to render GW react app.

or using an iframe

**Comment by ObservedObserver** [comment]
I think it is easy to support it directly in Graphic Walker, but requires a lot of testing
