### ISSUE TITLE
feature request: text mark and channel

### ISSUE THREAD

**Issue by declann** [Kanaries/graphic-walker#66]
Hi,

graphic-walker features many marks but not text.

I find text mark critical for some key visuals, starting with the 'grid of formulae' "picture" here:

https://observablehq.com/@declann/some-cashflows

![image](https://user-images.githubusercontent.com/353214/235049912-92a59e31-841b-475a-a5f3-874a27d4d3c0.png)

Would there be a difficulty supporting a text mark?

+Creating a separate issue for facets.

Thanks for the epic tool and really epic interface !
Very excited to discover this.

Regards,
Declan

**Comment by declann** [comment]
In case my graph/usecase looks trivial to do outside of graphic-walker: in my real usecase users should be able to alter the y axis*, so graphic-walker UI good, +numbers will be re-calculated so embeddable graphic-walker is also critical.

* above showing different months, but a user might want different scenarios on y axis (for a given month) instead.

**Comment by ObservedObserver** [comment]
will be added in version 0.3.3

**Comment by declann** [comment]
Will there be format control? https://vega.github.io/vega-lite/docs/format.html#formatting-text-marks-and-tooltips

**Comment by declann** [comment]
Super stuff! :)
