### ISSUE TITLE
feature request: facets by row/col

### ISSUE THREAD

**Issue by declann** [Kanaries/graphic-walker#67]
Hi,

Key visuals of numbers I'd love to reproduce in graphic-walker - and then integrate, rely on row facets, see 'row facet of formulae' "picture".

https://observablehq.com/@declann/some-cashflows

(+ text mark/channel, issue #66 )

What are the challenges to add row/col facets?

Thanks!
Declan

**Comment by declann** [comment]
For example, Voyager supports facets by row/col and text channel (#66). So does its underlying CompassQL.
A high-level take on how the graphic-walker stack diverges(?) from the Voyager stack would be very interesting to me.

**Comment by ObservedObserver** [comment]
Graphic Walker has already supports rows and columns facets. it is embedded into "axis", try to more than dragge two dimensions in x-axis or y-axis and you will see it.

**Comment by declann** [comment]
Neat UI choice. Thanks!
