### ISSUE TITLE
feature requests: independent scales option, legend on/off option

### ISSUE THREAD

**Issue by declann** [Kanaries/graphic-walker#69]
Hi, an option to use independent scales in facets would be useful, e.g. in the following chart we can't see the employees marks because the scale for other formulae is too big.

![image](https://user-images.githubusercontent.com/353214/235491019-2ea4bbbd-d013-4564-ab01-691f670df75a.png)

This is chart 2 in https://gist.github.com/declann/3e973796671f81d332c2ce36e3471e27

In this chart it's also useful to be able to remove legend as the color channel is redundant.

Is there a wish for this level of flexibility into graphic walker?

If not, I can probably do vega lite spec patching, supposing I embed graphic walker.

Thanks
Declan

**Comment by declann** [comment]
@k6sdevbob this might be like the requirement for what you did for the zero scales baseline #63 
Would it be nice to group some axis/scale options like this in UI?

**Comment by ObservedObserver** [comment]
For now, `graphic-walker` allows user to decide which visual channel need to share domain/range in different facets.


![image](https://github.com/Kanaries/graphic-walker/assets/22167673/170ed25a-75a6-4c4f-9a84-e1fec7e0096d)

![image](https://github.com/Kanaries/graphic-walker/assets/22167673/71267f77-665c-47fd-8641-48981ba43e3b)
