### ISSUE TITLE
Can it be used a Svelte component? 

### ISSUE THREAD

**Issue by SaraiQX** [Kanaries/graphic-walker#81]
Hi Kanaries team,
Hopefully this question as titled is not totally nonsense😂
Many thanks!

**Comment by ObservedObserver** [comment]
In version `0.3.9` you can use

```ts
import { embedGraphicWalker } from '@kanaries/graphic-walker'
embedGraphicWalker(document.querySelector<HTMLDivElement>('#app')!)
```

to render a graphic-walker component, which can be used in any frontend framework
