### ISSUE TITLE
Tooltip will show "Nan" for aggregated metrics, and "details" zone only show the latest field

### ISSUE THREAD

**Issue by Baoqi** [Kanaries/graphic-walker#84]
Reproducible by https://graphic-walker.kanaries.net/

The tooltip don't show the correct aggregated numbers.    And another small problem is: even I drop several fields into the "details" zone, it will only show the latest one.

<img width="1181" alt="2023-06-01 10 21 20" src="https://github.com/Kanaries/graphic-walker/assets/4434603/c86f808a-23e3-462e-b692-c9c663931415">

**Comment by AntoineYANG** [comment]
Thanks for the issue. I'll be working on it soon,
